title: Kann das Transhumanistische Argument gegen den Speziesismus überzeugen?
short: "Dieser kurze Essay war meine Abschlussarbeit in einer zweitsemestrigen LV zu wissenschaftlichem arbeiten in der Philosophie. Er kritisiert ein Argument des Transhumanismus gegen den Speziesismus."
date: 21.07.2022
tags:
    - essay
    - de 
    - transhumanismus
    - speziesismus
