title: An Argument against Speciesism based on Husserls Transcendental Intersubjectivity
short: "This was my final essay for a fantastic 2nd semester seminar on Husserls Cartesian Meditations, which was my first exposure to phenomenology. The essay mostly deals with Husserls transcendental intersubjectivity and attempts to create the basis for an argument against speciecism based on transcendental intersubjectivity."
date: 20.07.2022
tags:
    - essay
    - en
    - husserl
    - phenomenology
    - meditations
